/*
 * Consumer Data Standards
 *
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ConsumerDataStandards.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class BankingAccountDetail : BankingAccount, IEquatable<BankingAccountDetail>
    { 
        /// <summary>
        /// The unmasked BSB for the account.  Is expected to be formatted as digits only with leading zeros included and no punctuation or spaces
        /// </summary>
        /// <value>The unmasked BSB for the account.  Is expected to be formatted as digits only with leading zeros included and no punctuation or spaces</value>
        [DataMember(Name="bsb")]
        public string Bsb { get; set; }

        /// <summary>
        /// The unmasked account number for the account.  Should not be supplied if the account number is a PAN requiring PCI compliance. Is expected to be formatted as digits only with leading zeros included and no punctuation or spaces
        /// </summary>
        /// <value>The unmasked account number for the account.  Should not be supplied if the account number is a PAN requiring PCI compliance. Is expected to be formatted as digits only with leading zeros included and no punctuation or spaces</value>
        [DataMember(Name="accountNumber")]
        public string AccountNumber { get; set; }

        /// <summary>
        /// Optional field to indicate if this account is part of a bundle that is providing additional benefit for to the customer
        /// </summary>
        /// <value>Optional field to indicate if this account is part of a bundle that is providing additional benefit for to the customer</value>
        [DataMember(Name="bundleName")]
        public string BundleName { get; set; }

        /// <summary>
        /// The type of structure to present account specific fields.
        /// </summary>
        /// <value>The type of structure to present account specific fields.</value>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum SpecificAccountUTypeEnum
        {
            
            /// <summary>
            /// Enum TermDepositEnum for termDeposit
            /// </summary>
            [EnumMember(Value = "termDeposit")]
            TermDepositEnum = 1,
            
            /// <summary>
            /// Enum CreditCardEnum for creditCard
            /// </summary>
            [EnumMember(Value = "creditCard")]
            CreditCardEnum = 2,
            
            /// <summary>
            /// Enum LoanEnum for loan
            /// </summary>
            [EnumMember(Value = "loan")]
            LoanEnum = 3
        }

        /// <summary>
        /// The type of structure to present account specific fields.
        /// </summary>
        /// <value>The type of structure to present account specific fields.</value>
        [DataMember(Name="specificAccountUType")]
        public SpecificAccountUTypeEnum? SpecificAccountUType { get; set; }

        /// <summary>
        /// Gets or Sets TermDeposit
        /// </summary>
        [DataMember(Name="termDeposit")]
        public BankingTermDepositAccount TermDeposit { get; set; }

        /// <summary>
        /// Gets or Sets CreditCard
        /// </summary>
        [DataMember(Name="creditCard")]
        public BankingCreditCardAccount CreditCard { get; set; }

        /// <summary>
        /// Gets or Sets Loan
        /// </summary>
        [DataMember(Name="loan")]
        public BankingLoanAccount Loan { get; set; }

        /// <summary>
        /// Gets or Sets Features
        /// </summary>
        [DataMember(Name="features")]
        public List<BankingAccountFeature> Features { get; set; }

        /// <summary>
        /// Gets or Sets Fees
        /// </summary>
        [DataMember(Name="fees")]
        public List<BankingAccountFee> Fees { get; set; }

        /// <summary>
        /// Gets or Sets DepositRates
        /// </summary>
        [DataMember(Name="depositRates")]
        public List<BankingAccountDepositRate> DepositRates { get; set; }

        /// <summary>
        /// Gets or Sets LendingRates
        /// </summary>
        [DataMember(Name="lendingRates")]
        public List<BankingAccountLendingRate> LendingRates { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name="address")]
        public CommonPhysicalAddress Address { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BankingAccountDetail {\n");
            sb.Append("  Bsb: ").Append(Bsb).Append("\n");
            sb.Append("  AccountNumber: ").Append(AccountNumber).Append("\n");
            sb.Append("  BundleName: ").Append(BundleName).Append("\n");
            sb.Append("  SpecificAccountUType: ").Append(SpecificAccountUType).Append("\n");
            sb.Append("  TermDeposit: ").Append(TermDeposit).Append("\n");
            sb.Append("  CreditCard: ").Append(CreditCard).Append("\n");
            sb.Append("  Loan: ").Append(Loan).Append("\n");
            sb.Append("  Features: ").Append(Features).Append("\n");
            sb.Append("  Fees: ").Append(Fees).Append("\n");
            sb.Append("  DepositRates: ").Append(DepositRates).Append("\n");
            sb.Append("  LendingRates: ").Append(LendingRates).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((BankingAccountDetail)obj);
        }

        /// <summary>
        /// Returns true if BankingAccountDetail instances are equal
        /// </summary>
        /// <param name="other">Instance of BankingAccountDetail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BankingAccountDetail other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Bsb == other.Bsb ||
                    Bsb != null &&
                    Bsb.Equals(other.Bsb)
                ) && 
                (
                    AccountNumber == other.AccountNumber ||
                    AccountNumber != null &&
                    AccountNumber.Equals(other.AccountNumber)
                ) && 
                (
                    BundleName == other.BundleName ||
                    BundleName != null &&
                    BundleName.Equals(other.BundleName)
                ) && 
                (
                    SpecificAccountUType == other.SpecificAccountUType ||
                    SpecificAccountUType != null &&
                    SpecificAccountUType.Equals(other.SpecificAccountUType)
                ) && 
                (
                    TermDeposit == other.TermDeposit ||
                    TermDeposit != null &&
                    TermDeposit.Equals(other.TermDeposit)
                ) && 
                (
                    CreditCard == other.CreditCard ||
                    CreditCard != null &&
                    CreditCard.Equals(other.CreditCard)
                ) && 
                (
                    Loan == other.Loan ||
                    Loan != null &&
                    Loan.Equals(other.Loan)
                ) && 
                (
                    Features == other.Features ||
                    Features != null &&
                    Features.SequenceEqual(other.Features)
                ) && 
                (
                    Fees == other.Fees ||
                    Fees != null &&
                    Fees.SequenceEqual(other.Fees)
                ) && 
                (
                    DepositRates == other.DepositRates ||
                    DepositRates != null &&
                    DepositRates.SequenceEqual(other.DepositRates)
                ) && 
                (
                    LendingRates == other.LendingRates ||
                    LendingRates != null &&
                    LendingRates.SequenceEqual(other.LendingRates)
                ) && 
                (
                    Address == other.Address ||
                    Address != null &&
                    Address.Equals(other.Address)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Bsb != null)
                    hashCode = hashCode * 59 + Bsb.GetHashCode();
                    if (AccountNumber != null)
                    hashCode = hashCode * 59 + AccountNumber.GetHashCode();
                    if (BundleName != null)
                    hashCode = hashCode * 59 + BundleName.GetHashCode();
                    if (SpecificAccountUType != null)
                    hashCode = hashCode * 59 + SpecificAccountUType.GetHashCode();
                    if (TermDeposit != null)
                    hashCode = hashCode * 59 + TermDeposit.GetHashCode();
                    if (CreditCard != null)
                    hashCode = hashCode * 59 + CreditCard.GetHashCode();
                    if (Loan != null)
                    hashCode = hashCode * 59 + Loan.GetHashCode();
                    if (Features != null)
                    hashCode = hashCode * 59 + Features.GetHashCode();
                    if (Fees != null)
                    hashCode = hashCode * 59 + Fees.GetHashCode();
                    if (DepositRates != null)
                    hashCode = hashCode * 59 + DepositRates.GetHashCode();
                    if (LendingRates != null)
                    hashCode = hashCode * 59 + LendingRates.GetHashCode();
                    if (Address != null)
                    hashCode = hashCode * 59 + Address.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(BankingAccountDetail left, BankingAccountDetail right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(BankingAccountDetail left, BankingAccountDetail right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
