/*
 * Consumer Data Standards
 *
 * API sets created by the Australian Consumer Data Standards to meet the needs of the Consumer Data Right
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace ConsumerDataStandards.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CommonPersonDetail : CommonPerson, IEquatable<CommonPersonDetail>
    { 
        /// <summary>
        /// At least one record is required
        /// </summary>
        /// <value>At least one record is required</value>
        [Required]
        [DataMember(Name="phoneNumbers")]
        public List<CommonPhoneNumber> PhoneNumbers { get; set; }

        /// <summary>
        /// May be empty
        /// </summary>
        /// <value>May be empty</value>
        [Required]
        [DataMember(Name="emailAddresses")]
        public List<CommonEmailAddress> EmailAddresses { get; set; }

        /// <summary>
        /// Must contain at least one address. One and only one address may have the purpose of REGISTERED. Zero or one, and no more than one, record may have the purpose of MAIL. If zero then the REGISTERED address is to be used for mail
        /// </summary>
        /// <value>Must contain at least one address. One and only one address may have the purpose of REGISTERED. Zero or one, and no more than one, record may have the purpose of MAIL. If zero then the REGISTERED address is to be used for mail</value>
        [Required]
        [DataMember(Name="physicalAddresses")]
        public List<CommonPhysicalAddressWithPurpose> PhysicalAddresses { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CommonPersonDetail {\n");
            sb.Append("  PhoneNumbers: ").Append(PhoneNumbers).Append("\n");
            sb.Append("  EmailAddresses: ").Append(EmailAddresses).Append("\n");
            sb.Append("  PhysicalAddresses: ").Append(PhysicalAddresses).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public  new string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CommonPersonDetail)obj);
        }

        /// <summary>
        /// Returns true if CommonPersonDetail instances are equal
        /// </summary>
        /// <param name="other">Instance of CommonPersonDetail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CommonPersonDetail other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PhoneNumbers == other.PhoneNumbers ||
                    PhoneNumbers != null &&
                    PhoneNumbers.SequenceEqual(other.PhoneNumbers)
                ) && 
                (
                    EmailAddresses == other.EmailAddresses ||
                    EmailAddresses != null &&
                    EmailAddresses.SequenceEqual(other.EmailAddresses)
                ) && 
                (
                    PhysicalAddresses == other.PhysicalAddresses ||
                    PhysicalAddresses != null &&
                    PhysicalAddresses.SequenceEqual(other.PhysicalAddresses)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (PhoneNumbers != null)
                    hashCode = hashCode * 59 + PhoneNumbers.GetHashCode();
                    if (EmailAddresses != null)
                    hashCode = hashCode * 59 + EmailAddresses.GetHashCode();
                    if (PhysicalAddresses != null)
                    hashCode = hashCode * 59 + PhysicalAddresses.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CommonPersonDetail left, CommonPersonDetail right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CommonPersonDetail left, CommonPersonDetail right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
